add statosio
cdnjs/tutorials pull request #44
Opened 2020-12-13 11:21 UTC by a6b8

- fix tables, 
- add sri,
- json new line

2020-12-13 12:34 UTC, MattIPv4 commented
FYI, in future you don't need to close the PR and open a new one, the old one was updated and was fine to leave open for a second review 👍

2020-12-14 23:54 UTC, MattIPv4 requested changes
In a few places you use bullet points when they aren't really part of a list -- this seems like an odd style choice for the content? If they're meant to be subheadings, maybe bold would be better?

E.g. `- Option explained`

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/change-style-to-dark-mode/index.md
> +[Change style to dark-mode](https://d3.statosio.com/tutorials/change-style.html)
```suggestion
```
I don't think we need this link, as this is just the same tutorial as what we're currently showing?

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/create-a-simple-point-chart/index.md
> +[Create a simple point chart](https://d3.statosio.com/tutorials/simple-point-chart.html)
```suggestion
```
No need to link to identical content, just confuses the reader

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/create-a-simple-stacked-bar-chart/index.md
> +[Create simple stacked bar chart](https://d3.statosio.com/tutorials/simple-stacked-bar-chart.html)
```suggestion
```
No need for link

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/create-a-simple-stacked-bar-chart/index.md
> +List of all "show" Options: [here](https://d3.statosio.com/options/index.html#show)s
```suggestion
List of all "show" Options: [here](https://d3.statosio.com/options/index.html#show)
```
Random `s`?

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/select-and-change-position-of-columns/index.md
> +[Select and change position of columns](https://d3.statosio.com/tutorials/select-data.html)
```suggestion
```
Remove duplicate content link

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/select-and-change-position-of-columns/index.md
> +
```suggestion
```
Remove extra blank lines at end of file

2020-12-14 23:54 UTC, MattIPv4 commented on statosio/sort-dataset-by-values/index.md
> +[Sort dataset by values](https://d3.statosio.com/tutorials/sort-data.html)
```suggestion
```
Rm dupe content link

2020-12-15 03:45 UTC, a6b8 commented
> In a few places you use bullet points when they aren't really part of a list -- this seems like an odd style choice for the content? If they're meant to be subheadings, maybe bold would be better?
> 
> E.g. `- Option explained`


thanks for the fast reply

- removed bullet points.
- removed links
- removed "s"

2020-12-17 21:17 UTC, MattIPv4 requested changes
Tyvm :)

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-bar-chart/index.md
> +![# d3.statosio](https://d3.statosio.com/assets/images/example-bar-400.jpg)<br>
```suggestion
![# d3.statosio](https://d3.statosio.com/assets/images/example-bar-400.jpg)
```
br not needed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-bar-chart/index.md
> +``````
Extra fences need removing

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-point-chart/index.md
> +![# d3.statosio](https://d3.statosio.com/assets/images/example-point-400.jpg)<br>
```suggestion
![# d3.statosio](https://d3.statosio.com/assets/images/example-point-400.jpg)
```
br not needed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-point-chart/index.md
> +``````
Extra fences need removing

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-stacked-bar-chart/index.md
> +[Create simple stacked bar chart](https://d3.statosio.com/tutorials/simple-stacked-bar-chart.html)
This link still needs removing

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-stacked-bar-chart/index.md
> +![# d3.statosio](https://d3.statosio.com/assets/images/example-stacked-bar-400.jpg)<br>
```suggestion
![# d3.statosio](https://d3.statosio.com/assets/images/example-stacked-bar-400.jpg)
```
br not needed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/create-a-simple-stacked-bar-chart/index.md
> +``````
extra fences need removing

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/select-and-change-position-of-columns/index.md
> +![# d3.statosio](https://d3.statosio.com/assets/images/example-select-400.jpg)<br>
```suggestion
![# d3.statosio](https://d3.statosio.com/assets/images/example-select-400.jpg)
```
br not needed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/select-and-change-position-of-columns/index.md
> +``````
Extra fences need to be removed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/sort-dataset-by-values/index.md
> +![# d3.statosio](https://d3.statosio.com/assets/images/example-sort-400.jpg)<br>
```suggestion
![# d3.statosio](https://d3.statosio.com/assets/images/example-sort-400.jpg)
```
br isnt needed

2020-12-17 21:17 UTC, MattIPv4 commented on statosio/sort-dataset-by-values/index.md
> +``````
Extra fences need removing

2020-12-23 01:21 UTC, MattIPv4 approved these changes
Sorry for the delay -- all lgtm, tyvm!

2020-12-23 01:21 UTC, merged